name: i2k-2020
channels:
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.7
  - pyopencl
  - ocl-icd-system
  - cudatoolkit=10.1.*
  - cudnn=7.6.*
  - jupyter
  - pip
  - pip:
    - tensorflow==2.3.*
    - csbdeep
    - stardist
    - gputools